#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Check Disk Space

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Check Folder Size
      run: |
        echo "Checking /etc"
        cd /etc
        sudo du -h -d 2 | sort -nr
        echo "Checking /usr"
        cd /usr
        sudo du -h -d 2 | sort -nr
        echo "Checking /opt"
        cd /opt
        sudo du -h -d 2 | sort -nr
    
    - name: Clean disk space
      run: |
        df -hT
        docker rmi `docker images -q`
        df -hT
        sudo rm -rf /etc/apt/sources.list.d/*
        df -hT
        sudo rm -rf /etc/mysql
        df -hT
        sudo rm -rf /etc/php
        df -hT
        sudo rm -rf /usr/share/dotnet
        df -hT
        sudo rm -rf /usr/local/lib/android
        df -hT
        sudo rm -rf /opt/ghc
        df -hT
